### ISSUE TITLE
Camperbot quiet thresholds

### ISSUE THREAD

**Issue by combsco** [freeCodeCamp/camperbot#101] opened 2016-07-13 17:58 UTC
When the chat channel has high traffic Camperbot should be silenced from spamming mass body of texts to commit a CoC violation of spamming either on purpose, accidental or informational.

This could be also resolved with a prefix but combining both will keep the chat from being overloaded by a rogue Camperbot command.

Ex: If the chat is moving at a high rate, do not allow camperbot to spam more than 3 lines of text, no images, no gifs.

**Comment by raisedadead** [comment] 2016-07-20 13:06
Duplicate of #22

**Comment by combsco** [comment] 2016-07-20 14:26
This isn't a duplicate of #22 

#22 is about duplicate messages and making a debounce function. If you've read the issue I posted it's about shutting camperbot up when the chat is moving at a high rate to now create his own walls of spam.

**Comment by raisedadead** [comment] 2016-07-20 14:29
Well this issue will soon be a wontfix, because camperbot wont be displaying any help any longer.
refer #103

**Closed** 2017-01-18 19:46 UTC
